apiVersion: v1
kind: Service
metadata:
  name: master-multipaper-service
  labels:
    {{- include "cloudland-crafters.master.labels" . | nindent 4 }}
spec:
  type: {{ .Values.master.service.server.type }}
  ports:
    - port: {{ .Values.master.service.server.port }}
      targetPort: {{ .Values.master.service.server.targetPort }}
      protocol: TCP
      name: server
  selector:
    {{- include "cloudland-crafters.master.selectorLabels" . | nindent 4 }}
