apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudland-crafters.fullname" . }}
  labels:
    {{- include "cloudland-crafters.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "cloudland-crafters.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cloudland-crafters.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.master.image.repository }}:{{ .Values.master.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.master.image.pullPolicy }}
          ports:
            - name: server
              containerPort: {{ .Values.master.service.port }} #35353
              protocol: TCP
            - name: proxy
              containerPort: {{ .Values.master.service.proxy.port }} #25565
              protocol: TCP
          