apiVersion: apps/v1
kind: Deployment
metadata:
  name: slave-server
  labels:
    {{- include "cloudland-crafters.server.labels" . | nindent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels:
      {{- include "cloudland-crafters.server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cloudland-crafters.server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-slave
          image: "{{ .Values.slave.image.repository }}:{{ .Values.slave.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.slave.image.pullPolicy }}
          stdin: true
          ports:
            - name: server-slave
              containerPort: {{ .Values.slave.service.server.port }} #25565
              protocol: TCP
          VolumeMounts:
            - mountPath: /multipaper/data
              subPath: data
              name: multipaper-config
      volumes:
        - name: multipaper-config
          configMap:
            name: server-config
