apiVersion: apps/v1
kind: Deployment
metadata:
  name: slave-server
  labels:
    {{- include "cloudland-crafters.server.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cloudland-crafters.server.selectorLabels" . | nindent 6 }}
          imagePullPolicy: {{ .Values.slave.image.pullPolicy }}
          stdin: true
          ports:
            - name: server-slave
              containerPort: {{ .Values.slave.service.server.port }} #25565
              protocol: TCP
          resources:
            limits:
              cpu: 1500m
            requests:
              cpu: 1000m