apiVersion: v1
kind: Service
metadata:
  name: slave-multipaper-service
  labels:
    {{- include "cloudland-crafters.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.slave.service.server.type }}
  ports:
    - port: {{ .Values.slave.service.server.port }}
      targetPort: {{ .Values.slave.service.server.targetPort }}
      protocol: TCP
      name: slave-server
  selector:
    {{- include "cloudland-crafters.server.selectorLabels" . | nindent 4 }}
