apiVersion: apps/v1
kind: Deployment
metadata:
  name: slave-server
  labels:
    {{- include "cloudland-crafters.server.labels" . | nindent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels:
      {{- include "cloudland-crafters.server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cloudland-crafters.server.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - name: {{ .Chart.Name }}-slave
          image: "{{ .Values.slave.image.repository }}:{{ .Values.slave.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.slave.image.pullPolicy }}
          stdin: true
          ports:
            - name: server-slave
              containerPort: {{ .Values.slave.service.server.port }} #25565
              protocol: TCP
          volumeMounts:
            - mountPath: /multipaper/data/eula.txt
              subPath: eula.txt
              name: multipaper-eula
            - mountPath: /multipaper/data/server.properties
              subPath: server.properties
              name: multipaper-properties
            - mountPath: /multipaper/data/spigot.yml
              subPath: spigot.yml
              name: multipaper-spigot
      volumes:
        - name: multipaper-eula
          configMap:
            name: server-config
            items:
              - key: eula.txt
                path: eula.txt
        - name: multipaper-properties
          configMap:
            name: server-config
            items:
              - key: server.properties
                path: server.properties
        - name: multipaper-spigot
          configMap:
            name: server-config
            items:
              - key: spigot.yml
                path: spigot.yml