apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudland-crafters.fullname" . }}
  labels:
    {{- include "cloudland-crafters.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      slave
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cloudland-crafters.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-slave
          image: "{{ .Values.slave.image.repository }}:{{ .Values.slave.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.slave.image.pullPolicy }}
          ports:
            - name: server-slave
              containerPort: {{ .Values.slave.service.server.port }} #25565
              protocol: TCP
